### ISSUE TITLE
Easier read-write cloning

### ISSUE THREAD

**Issue by pengwynn** [mislav/coral#1]
I'm curious about your workflow with `coral clone`.

I noticed the command [uses `git://`](https://github.com/mislav/coral/blob/master/libexec/coral-clone#L32) instead of `https://`, which means you have to update the origin remote URL before you can push to the canonical repository, right?

**Comment by mislav** [comment]
I usually clone other people's repos and use `hub fork`. That adds the "mislav" remote with push access.

If I get commit access to another's repo, I manually set my pushUrl.

**Comment by mislav** [comment]
How do you handle auth with HTTPS? I only use SSH for write.

```
$ git remote -v
origin  git://github.com/pengwynn/faraday_middleware.git (fetch)
origin  git@github.com:pengwynn/faraday_middleware.git (push)
```

**Comment by pengwynn** [comment]
We've switched to HTTPS since it handles both read/write. I was using the OSX Keychain credential helper, but now the wizards have hooked me up with a [boxen variant](https://github.com/pengwynn/dotfiles/blob/master/git/gitconfig.symlink#L88-L89). It's no biggie. I can do the updates manually since 80% of the time I'm cloning someone else's code, too. I'm just moving all my current non-GitHub repos into coral because I :heart: this workflow. Gonna close this out.
